/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "MyPerf4J"
include(":MyPerf4J-Core")
include(":MyPerf4J-Base")
include(":MyPerf4J-Benchmark")
include(":MyPerf4J-ASM")
